apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brokerone-kafka-dispatcher-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/brendoncardoso/brokerone-kafka-dispatcher.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: local
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true